# Generated by Django 5.0.6 on 2024-07-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_pedido_estado_alter_pedido_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
