# Generated by Django 5.0.6 on 2024-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_pedido_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(choices=[('ARICA Y PARINACOTA', 'arica y parinacota'), ('TARAPACA', 'tarapaca'), ('ANTOFAGASTA', 'antofagasta'), ('ATACAMA', 'atacama'), ('COQUIMBO', 'coquimbo'), ('VALPARAISO', 'valparaiso'), ('METROPOLITANA', 'metropolitana'), ("BERNARDO O'HIGGINS", "bernardo o'higgins"), ('MAULE', 'maule'), ('BIO-BIO', 'bio-bio'), ('ARAUCANIA', 'araucania'), ('LOS RIOS', 'los rios'), ('LOS LAGOS', 'los lagos'), ('AYSÉN', 'aysen'), ('MAGALLANES', 'magallanes')], default='BIO-BIO', max_length=100),
        ),
    ]
